### ISSUE TITLE
Unexpected character '@' (10:0) when used with reactjs

### ISSUE THREAD

**Issue by rachit1994** [luxp/mathquill-webpack#1]
hi, 
i am using your module with reactjs and webpack which is throwing following error... please help

```
ERROR in ./~/mathquill/mathquill.css
Module parse failed: /home/rachit/rachit/mathInput/node_modules/mathquill/mathquill.css Unexpected character '@' (10:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '@' (10:0)
    at Parser.pp$4.raise (/home/rachit/rachit/mathInput/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/home/rachit/rachit/mathInput/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/home/rachit/rachit/mathInput/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/home/rachit/rachit/mathInput/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/home/rachit/rachit/mathInput/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/home/rachit/rachit/mathInput/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/home/rachit/rachit/mathInput/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/rachit/rachit/mathInput/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/rachit/rachit/mathInput/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/rachit/rachit/mathInput/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
 @ ./~/mathquill/index.js 3:0-26

```

**Comment by luxp** [comment]
It seems to be a problem with the webpack loaders config. I tested this issue with the loaders config below and it works fine. You can try it.

``` js
loaders: [
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      },
      {
        test: /\.sass/,
        loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded&indentedSyntax'
      },
      {
        test: /\.scss/,
        loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded'
      },
      {
        test: /\.less/,
        loader: 'style-loader!css-loader!less-loader'
      },
      {
        test: /\.styl/,
        loader: 'style-loader!css-loader!stylus-loader'
      },
      {
        test: /\.(png|jpg|gif|eot|ttf|otf|woff|woff2)$/,
        loader: 'url-loader?limit=8192'
      },
      {
        test: /\.(mp4|ogg|svg)$/,
        loader: 'file-loader'
      }
    ]
```

**Comment by rachit1994** [comment]
even after this some packages needed to be installed (css-loader,file-loader,style-loader,url-loader)
**package.json**

```
  "dependencies": {
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "jquery": "^2.2.3",
    "react": "^15.3.2",
    "react-dom": "^15.3.2",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.2"
  }
```

and this even webpack needed to be updated with :       

> resolve: {
>         extensions: ['', '.js', '.jsx', '.css'],
>         modulesDirectories: [
>           'node_modules'
>         ]  
>     }

now its working perfect :100: , my webpack looks like this : 

```
var config = {
   entry: './main.js',

   output: {
      path:'./',
      filename: 'index.js',
   },

   devServer: {
      inline: true,
      port: 8080
   },

   module: {
      loaders: [
         {
            test: /\.jsx?$/,
            exclude: /node_modules/,
            loader: 'babel',

            query: {
               presets: ['es2015', 'react']
            }
         },
          {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      },
      {
        test: /\.sass/,
        loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded&indentedSyntax'
      },
      {
        test: /\.scss/,
        loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded'
      },
      {
        test: /\.less/,
        loader: 'style-loader!css-loader!less-loader'
      },
      {
        test: /\.styl/,
        loader: 'style-loader!css-loader!stylus-loader'
      },
      {
        test: /\.(png|jpg|gif|eot|ttf|otf|woff|woff2)$/,
        loader: 'url-loader?limit=8192'
      },
      {
        test: /\.(mp4|ogg|svg)$/,
        loader: 'file-loader'
      }],
      resolve: {
        extensions: ['', '.js', '.jsx', '.css'],
        modulesDirectories: [
          'node_modules'
        ]        
    }

   }
}

module.exports = config;

```
